config/routes.rb
Rails.application.routes.draw do
  # get 'games/index'
  # get 'games/show'
  # get 'games/new'
  # get 'games/create'
  # get 'games/edit'
  # get 'games/update'
  # get 'games/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "games#index"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :games do
    resources :bookings, only: [:create]
    # resources :reviews, only: [:create]
    resources :reviews, shallow: true
  end

  get "my_games", to: "games#my_index"
  get "my_bookings", to: "bookings#my_index"
  patch "bookings/:id/accept", to: "bookings#accept", as: "booking_accept"
  patch "bookings/:id/refuse", to: "bookings#refuse", as: "booking_refuse"
end

app/views/shared/_bookings.html.erb
<div class="card-booking mt-3 p-2">
  <div class="d-flex justify-content-between">
    <h5>From <%= booking.start_at.strftime("%d/%m/%Y")  %> to <%= booking.end_at.strftime("%d/%m/%Y")  %></h2>
    <% if booking.status === "pending" %>
      <div class="d-flex">
        <%= link_to booking_accept_path(booking), data: { turbo_method: :patch } do %>
          <i class="fa-solid fa-check text-success p-2"></i>
        <% end %>
        <%= link_to booking_refuse_path(booking), data: { turbo_method: :patch } do %>
          <i class="fa-solid fa-x text-danger p-2"></i>
        <% end %>
      </div>
    <% elsif booking.status === "accepted" %>
      <span class="text-success text-accepted">Accepted</span>
    <% end %>
  </div>
  <span><%= booking.user.first_name %>, at <%= booking.user.city %></span>
</div>

app/views/shared/_card.html.erb
<div class="container">
  <div class="row">
    <% @games.where(user: current_user).each do |game| %>
      <div class="col-md-3 mb-4">
        <%= link_to(game_path(game), class: "card-trip") do %>
          <div class="card-trip">
            <% if game.photo.attached? %>
              <%= cl_image_tag game.photo.key, class: "card-image mt-2 img-fluid", crop: :fill %>
            <% else %>
              <%= image_tag "des.jpg", class: "card-image mt-2 img-fluid", alt: "Default Game Image" %>
            <% end %>

            <div class="card-trip-infos border-top pt-3">
              <div>
                <h2><%= game.name %></h2>
                <p class="detail">Category: <%= game.category %></p>
                <p class="detail"> <%= "From #{game.number_of_players_min} to #{game.number_of_players_max}" %> Players</p>
              </div>
              <h2 class="card-trip-pricing text-right"><%= game.price %>€</h2>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="row">
  <% @games.each do |game| %>
    <div class="col-md-4 mb-4">
      <%= link_to(game_path(game), class: "card-trip") do %>
        <div class="card-trip">
          <% if game.photo.attached? %>
            <%= cl_image_tag game.photo.key, class: "card-image mt-2 img-fluid", crop: :fill %>
          <% else %>
            <%= image_tag "des.jpg", class: "card-image mt-2 img-fluid", alt: "Default Game Image" %>
          <% end %>

          <div class="card-trip-infos border-top pt-3">
            <% if game.user === current_user %>
              <% bookings_count = game.bookings.where(status: "pending").where("start_at >= ?", Time.now.midnight).count %>
              <% if bookings_count >   0 %>
                <span class="booking-infos"><%= pluralize(bookings_count, 'pending booking ') %>⌛</span>
              <% end %>
            <% end %>
            <div>
              <h2><%= game.name %></h2>
              <p class="detail">Category: <%= game.category %></p>
              <p class="detail">
              <i class="fas fa-users" aria-hidden="true"></i>
              <%= "#{game.number_of_players_min} - #{game.number_of_players_max}" %>
              </p>
            </div>
            <h2 class="card-trip-pricing text-right"><%= game.price %>€ per day</h2>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.lewagon.com/fr/lille?utm_adgroup=&utm_term=le%20wagon%20lille&utm_campaign=FR_|_France_|_BRAND_|_FR_|_S&utm_source=google&utm_medium=cpc&hsa_acc=9887519486&hsa_cam=20519477673&hsa_grp=157103928430&hsa_ad=673103371805&hsa_src=g&hsa_tgt=aud-1706814675334:kwd-1190011159638&hsa_kw=le%20wagon%20lille&hsa_mt=p&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAsIGrBhAAEiwAEzMlC54NFPhMVn_X9olC2pnVH5AReDqqvr-x3YqpoC9jNMq08Mshi1IJ0xoCw9QQAvD_BwE"><i class="fab fa-github"></i></a>
    <a href="https://www.lewagon.com/fr/lille?utm_adgroup=&utm_term=le%20wagon%20lille&utm_campaign=FR_|_France_|_BRAND_|_FR_|_S&utm_source=google&utm_medium=cpc&hsa_acc=9887519486&hsa_cam=20519477673&hsa_grp=157103928430&hsa_ad=673103371805&hsa_src=g&hsa_tgt=aud-1706814675334:kwd-1190011159638&hsa_kw=le%20wagon%20lille&hsa_mt=p&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAsIGrBhAAEiwAEzMlC54NFPhMVn_X9olC2pnVH5AReDqqvr-x3YqpoC9jNMq08Mshi1IJ0xoCw9QQAvD_BwE"><i class="fab fa-instagram"></i></a>
    <a href="https://www.lewagon.com/fr/lille?utm_adgroup=&utm_term=le%20wagon%20lille&utm_campaign=FR_|_France_|_BRAND_|_FR_|_S&utm_source=google&utm_medium=cpc&hsa_acc=9887519486&hsa_cam=20519477673&hsa_grp=157103928430&hsa_ad=673103371805&hsa_src=g&hsa_tgt=aud-1706814675334:kwd-1190011159638&hsa_kw=le%20wagon%20lille&hsa_mt=p&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAsIGrBhAAEiwAEzMlC54NFPhMVn_X9olC2pnVH5AReDqqvr-x3YqpoC9jNMq08Mshi1IJ0xoCw9QQAvD_BwE"><i class="fab fa-facebook"></i></a>
    <a href="https://www.lewagon.com/fr/lille?utm_adgroup=&utm_term=le%20wagon%20lille&utm_campaign=FR_|_France_|_BRAND_|_FR_|_S&utm_source=google&utm_medium=cpc&hsa_acc=9887519486&hsa_cam=20519477673&hsa_grp=157103928430&hsa_ad=673103371805&hsa_src=g&hsa_tgt=aud-1706814675334:kwd-1190011159638&hsa_kw=le%20wagon%20lille&hsa_mt=p&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAsIGrBhAAEiwAEzMlC54NFPhMVn_X9olC2pnVH5AReDqqvr-x3YqpoC9jNMq08Mshi1IJ0xoCw9QQAvD_BwE"><i class="fab fa-twitter"></i></a>
    <a href="https://www.lewagon.com/fr/lille?utm_adgroup=&utm_term=le%20wagon%20lille&utm_campaign=FR_|_France_|_BRAND_|_FR_|_S&utm_source=google&utm_medium=cpc&hsa_acc=9887519486&hsa_cam=20519477673&hsa_grp=157103928430&hsa_ad=673103371805&hsa_src=g&hsa_tgt=aud-1706814675334:kwd-1190011159638&hsa_kw=le%20wagon%20lille&hsa_mt=p&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAsIGrBhAAEiwAEzMlC54NFPhMVn_X9olC2pnVH5AReDqqvr-x3YqpoC9jNMq08Mshi1IJ0xoCw9QQAvD_BwE"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by La DreamTeam 🚀
  </div>
</div>

app/views/shared/_game_description_show.erb
  <div class="game-description">
  <div class="photo">
    <% if @game.photo.attached? %>
    <%= cl_image_tag @game.photo.key,  crop: :fill, class: "img-fluid" %>
    <% end %><br>
  </div>
  <div class="details">
    <span id="title">🃏 <%=  @game.name.upcase %> | <%= @game.user.first_name %> à <%= @game.user.city %> </span><br>
    <div class="details-text">Rent <%=  @game.name %> for <%= @game.price %>€ per day 😍<br></div>
    <div class="details-text">Category: <%= @game.category %><br></div>

    <p class="detail">
    <i class="fas fa-users" aria-hidden="true"></i>
      <%= "#{@game.number_of_players_min} - #{@game.number_of_players_max}" %>
    </p>

    <% if @game.user === current_user %>

    <div class="btns">
      <%# <%= link_to "Edit my game", edit_game_path, class:"edit-btn" %>
      <%# <%= link_to "Delete my announce", game_path(@game), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" }, class:"delete-btn" %>
      <%= link_to edit_game_path do %>
        <i class="fas fa-edit text-dark edit-btn edit-icon"></i>
      <% end %>
      <%= link_to game_path(@game), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
        <i class="fas fa-trash text-danger delete-btn"></i>
      <% end %>
    </div>

    <% end %>
  </div>
</div>
<div class="description-text mb-5 pb-5">
  <div class="row justify-content-between">
    <div class="col-8 pe-5 border-end">
      <i id="diamond" class="fa-solid fa-diamond"></i>
      <span class="description-title">Description</span><br>
      <div class="text"><%=  @game.description %></div>
    </div>
    <div class="col-4 px-5">
      <% if @game.user === current_user %>
        <i id="diamond" class="fa-solid fa-diamond"></i>

        <span class="description-title">Next bookings </span>

        <% bookings = @game.bookings.where(status: ["pending", "accepted"]).where("start_at >= ?", Time.now.midnight).order(:created_at) %>
        <% if bookings.any? %>
          <% bookings.each do |booking| %>
            <%= render "shared/bookings", booking: booking %>
          <% end %>
        <% else %>
          <div class="text">No bookings soon 😞</div>
        <% end %>
      <% else %>
        <i id="diamond" class="fa-solid fa-diamond"></i>
        <span class="description-title">Booking :</span><br><br>
        <div data-controller="dynamic-booking-price" data-dynamic-booking-price-price-value="<%= @game.price %>">
            <%= simple_form_for [@game, @booking],
                        html: { data: { controller: "datepicker" } } do |f| %>
              <input type="text" class="form-control" data-datepicker-target="dates" data-action="change->datepicker#setDates change->dynamic-booking-price#updatePrice">
              <%= f.input :start_at,
                    as: :string,
                    as: :hidden,
                    input_html: { data: { datepicker_target: "startTime",
                      dynamic_booking_price_target: "startTime"  } } %>
              <%= f.input :end_at,
                    as: :string,
                    as: :hidden,
                    input_html: { data: { datepicker_target: "endTime",
                      dynamic_booking_price_target: "endTime" } } %>
              <%= f.submit 'Ask for booking', class: 'submit-btn' %>
            <% end %>
              <p data-dynamic-booking-price-target="priceHolder" class="mt-4"></p>
          </div>
      <% end %>
    </div>
  </div>

app/views/shared/_map.html.erb
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mb-5 fixed-navbar">
  <div class="container-fluid">

  <div class="logo-title">
    <%= link_to games_path, class: "fa-solid fa-fire-flame-curved" do %>
      <i></i>
    <% end %>

      <%= link_to games_path, class: "navbar-brand" do %>
      <span class="fs-1 " id= "airgames-title">AirGames</span>
      <% end %>
  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <%= link_to "+ Add a new game", new_game_path, class: "nav-link text-black text-navbar" %>
        </li>
       <li class="nav-item dropdown">
  <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
    <% if current_user.profile_picture.attached? %>
      <%= image_tag current_user.profile_picture, class: "avatar", alt: "Profile" %>
    <% else %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/1752/1752751.png", class: "avatar", alt: "Default Profile" %>
    <% end %>
  </a>
  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
    <%= link_to "My games", my_games_path, class: "dropdown-item" %>
    <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
    <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
  </div>
</li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-navbar text-black" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_reviews.erb
 <div class="reviews">
  <%= simple_form_for [@game, @review] do |f| %>
    <%= f.input :comment %>
    <%= f.input :rating, as: :hidden %>
      <div class="my-3">
        <% Review::RATES.each do |index| %>
          <i id="<%= index %>" class="review-rating far fa-star"></i>
        <% end %>
      </div>
    <%= f.submit %>
  <% end %>
</div>


  <div class="comments-section">
    <h2>Comments</h2>
    <div class="rating">
      <div class="stars" data-rating="<%= @game.average_rating %>">
      <%# attribut HTML standard qui permet de stocker des informations supplémentaires dans le code HTML
      généralement pour une utilisation JavaScript ou pour transporter des données côté client %>
        <% (1..5).each do |star| %>
          <!-- Si la note moyenne est supérieure ou égale à l'indice de l'étoile, ajoute la classe ".filled" -->
          <span class="star <% if star <= @game.average_rating %>filled<% end %>">&#9733;</span>
        <% end %>
      </div>
    </div>
      <span><%= @game.average_rating %></span>
      <span> · <%= @game.reviews.count %> reviews</span>
<%# une card par review %>
  <div class="review-card">
    <% @game.reviews.each do |review| %>
        <strong><%= review.user.first_name %>:</strong>
        <%= time_ago = time_ago_in_words(review.updated_at) + " ago" %>
        <p><%= review.comment %></p>
        <div class="rating"><%= review.rating %></div>
    <% end %>
  </div>
</div>

app/views/shared/_reviews.html.erb
<%# form %>
 <div class="reviews">
  <%= simple_form_for [@game, @review], data: {turbo: false } do |f| %>
    <%= f.input :comment, label: 'Write a comment about your booking', input_html: { class: 'input-comment' } %>
    <%= f.input :rating, as: :hidden %>
      <div class="my-3">
        <% Review::RATES.each do |index| %>
          <i id="<%= index %>" class="review-rating far fa-star"></i>

        <% end %>
      </div>
    <%= f.submit 'Comment', class: 'submit-btn' %>

  <% end %>
</div>

<%# la moyenne %>
  <div class="comments-section" data-controller="stars-in-review-form">
    <h2 id="comment">Comments</h2>
    <div class="rating">
      <div class="stars" data-rating="<%= @game.average_rating %>">
      <%# attribut HTML standard qui permet de stocker des informations supplémentaires dans le code HTML
      généralement pour une utilisation JavaScript ou pour transporter des données côté client %>
        <% (1..5).each do |star| %>
          <!-- Si la note moyenne est supérieure ou égale à l'indice de l'étoile, ajoute la classe ".filled" -->
          <% filled_star_class = star <= @game.average_rating ? 'fas' : 'far' %>
        <i class="<%= filled_star_class %> fa-star"></i>        <% end %>
      </div>
    </div>
      <span><%= @game.average_rating %>/5</span>
      <span> · <%= @game.reviews.count %> reviews</span>

<%# previous comments %>
<div class="review-card">
  <% @game.reviews.reverse.each do |review| %>
    <strong><%= review.user.first_name %>:</strong>
    <span id="ago"><%= time_ago = time_ago_in_words(review.updated_at) + " ago" %></span>
    <p><%= review.comment %></p>
    <div class="rating">
      <% (1..5).each do |star| %>
        <% filled_star_class = star <= review.rating ? 'fas' : 'far' %>
        <i class="<%= filled_star_class %> fa-star"></i>
      <% end %>
    </div>
  <% end %>
</div>


</div>